definitions:
  audit.AuditResponseStatus:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  model_api_1.ModelResponse1:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths: {}
swagger: "2.0"
